version: "3.9"

services:
  db:
    container_name: postgres-db
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - meal_network

  dbadmin:
    container_name: pgadmin-meal
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5080:80
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - meal_network

  api:
    container_name: meal-api
    build:
      context: ./meal-api
      dockerfile: Dockerfile
    env_file:
      - ./meal-api/.env
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./meal-api/src:/app/src
    networks:
      - meal_network

networks:
  meal_network:
    driver: bridge
