version: "3.9"

services:
  api:
    container_name: meal-api
    build:
      context: ./meal-api
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./meal-api:/usr/src/app

  db:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./meal-db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./meal-db/pgdata:/var/lib/postgresql/data
      - ./meal-db/pgadmin:/var/lib/postgresql/admin

  dbadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5080:80
    env_file:
      - .env
    volumes:
      - ./meal-db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./pgadmin:/var/lib/pgadmin
